export const ENV = {
  SNAPSHOT_API_URL: process.env.SNAPSHOT_API_URL,
  PUBLIC_ENABLE_TESTNETS: process.env.PUBLIC_ENABLE_TESTNETS === "true",
  PUBLIC_THIRDWEB_CLIENT_ID: process.env.PUBLIC_THIRDWEB_CLIENT_ID,
  PUBLIC_WALLET_CONNECT_PROJECT_ID:
    process.env.PUBLIC_WALLET_CONNECT_PROJECT_ID ?? "",
};
